### ISSUE TITLE
Fix the footer UI

### ISSUE THREAD

**Issue by Maaz-Code** [rahul-n18/Student-Library#44] opened 2022-10-04 19:36 UTC
## Problems:
- Footer components in the Newsletter section are not of the correct sizes.
- Responsiveness for screen sizes > 992px and < 1500px needs to be fixed.

## Screenshots:
Newsletter footer:

![image](https://user-images.githubusercontent.com/65590762/193909566-718bd873-e55b-4e73-ae3a-c46c511e7b60.png)

![image](https://user-images.githubusercontent.com/65590762/193909480-4fb42e6b-04a8-4c3d-9af1-b7f52a78c12a.png)

![image](https://user-images.githubusercontent.com/65590762/193909427-c1c452a0-9b08-4d86-816e-735d43abe04e.png)
 
#### I would like to fix this by working on this and then create a PR regarding the same.

**Comment by rahul-n18** [comment] 2022-10-04 19:57
I have assigned this to you

**Comment by rahul-n18** [comment] 2022-10-05 07:25
this issue is cleared.

**Closed by rahul-n18** 2022-10-05 07:25 UTC

**Comment by Maaz-Code** [comment] 2022-10-05 07:47
@rahul-n18 I checked it. This issue is not solved, kindly re-open it.

**Comment by rahul-n18** [comment] 2022-10-05 08:07
@Maaz-Code the issue is being solved and it is in production

Thank you
